package com.atlbike.etl.util;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Properties;

/**
 * Default values are provided in the jar file and user overrides are maintained
 * in the 'user.home/etl' directory.
 * 
 * @author a8l8f
 */
public class ETLProperties extends Properties {

	private static ETLProperties instance = null;

	private static final String LOGIN_EMAIL_KEY = "nb.login.userEmail";
	private static final String LOGIN_PWD_KEY = "nb.login.password";

	private static final long serialVersionUID = -1377382212031801148L;
	private static String propertiesFileName = "nb.etl.properties";
	// private String loginUrlKey = "nb.etl.url.login";
	// private String membershipTypeKey = "nb.etl.membership.types";
	private String loginUrl = null;
	private String loginEmail = null;
	private String loginPwd = null;

	public static ETLProperties getInstance() {
		if (instance == null) {
			instance = new ETLProperties();
		}
		return instance;
	}

	public void load() {
		// Defaults come in first
		InputStream inputStream = ETLProperties.class
				.getResourceAsStream(propertiesFileName);
		try {
			load(inputStream);
		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			if (inputStream != null)
				try {
					inputStream.close();
				} catch (IOException e) {
					// ignore
				}
		}

		// Then bring in user overrides ...
		String userHomeFileName = System.getProperty("user.home") + "/etl/"
				+ propertiesFileName;
		File userHomeFile = new File(userHomeFileName);
		// ... but only if the file exists
		if (userHomeFile.exists()) {
			try {
				inputStream = new FileInputStream(userHomeFile);
				load(inputStream);
			} catch (FileNotFoundException e) {
				e.printStackTrace();
			} catch (IOException e) {
				e.printStackTrace();
			} finally {
				if (inputStream != null)
					try {
						inputStream.close();
					} catch (IOException e) {
						// ignore
					}
			}
		}

		setLoginEmail(getProperty(LOGIN_EMAIL_KEY));
		setLoginPwd(getProperty(LOGIN_PWD_KEY));
	}

	public void store() throws FileNotFoundException, IOException {
		File userPropsFile = null;
		userPropsFile = prepareUsersFile();
		OutputStream outputStream = new FileOutputStream(userPropsFile);
		store(outputStream, " Auto-generated by ETL Application");
	}

	/**
	 * Creates the file (and directory) if it doesn't exist and in any case will
	 * return the writable file for storing the properties.
	 * 
	 * @return
	 * @throws IOException
	 */
	private File prepareUsersFile() throws IOException {
		File propsFile;
		String userHome = System.getProperty("user.home") + "/etl";
		File userHomeDirectory = new File(userHome);
		if (!userHomeDirectory.exists()) {
			userHomeDirectory.mkdir();
		}
		String propsFileName = userHome + "/" + propertiesFileName;
		propsFile = new File(propsFileName);
		if (!propsFile.exists()) {
			propsFile.createNewFile();
		}
		return propsFile;
	}

	public String getLoginUrl() {
		return loginUrl;
	}

	public void setLoginUrl(String loginUrl) {
		this.loginUrl = loginUrl;
	}

	public String getLoginEmail() {
		return loginEmail;
	}

	public void setLoginEmail(String loginEmail) {
		this.loginEmail = loginEmail;
		setProperty(LOGIN_EMAIL_KEY, loginEmail);
	}

	public String getLoginPwd() {
		return loginPwd;
	}

	public void setLoginPwd(String loginPwd) {
		this.loginPwd = loginPwd;
		setProperty(LOGIN_PWD_KEY, loginPwd);
	}

	public boolean isAccountDefined() {
		if (loginEmail == null)
			return false;
		if (loginPwd == null)
			return false;
		if (loginEmail.trim().length() == 0)
			return false;
		if (loginPwd.trim().length() == 0)
			return false;
		return true;
	}

}
