package com.atlbike.etl.util;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.util.Properties;

/**
 * Default values are provided in the jar file and user overrides are 
 * maintained in the 'user.home/etl' directory.
 * 
 * @author a8l8f
 */
public class ETLProperties extends Properties {
	
	private static final long serialVersionUID = -1377382212031801148L;
	private static String propertiesFileName = "nb.etl.properties";
	private String loginUrlKey = "nb.etl.url.login";
	private String loginUrl = null;
	
	public void load() {
		loginUrl = "temp";
		put(loginUrlKey, loginUrl);
	}
	
	public void store() throws FileNotFoundException, IOException {
		File userPropsFile = null;
		userPropsFile = prepareUsersFile();
		OutputStream outputStream = new FileOutputStream(userPropsFile);
		store(outputStream, " Auto-generated by ETL Application");
	}

	/**
	 * Creates the file (and directory) if it doesn't exist and in any case
	 * will return the writable file for storing the properties.
	 * 
	 * @return
	 * @throws IOException
	 */
	private File prepareUsersFile() throws IOException {
		File propsFile;
		String userHome = System.getProperty("user.home")+"/etl";
		File userHomeDirectory = new File(userHome);
		if (!userHomeDirectory.exists()) {
			userHomeDirectory.mkdir();
		}
		String propsFileName = userHome+"/"+propertiesFileName;
		propsFile = new File(propsFileName);
		if (!propsFile.exists()) {
			propsFile.createNewFile();
		}
		return propsFile;
	}

	public String getLoginUrl() {
		return loginUrl;
	}

	public void setLoginUrl(String loginUrl) {
		this.loginUrl = loginUrl;
	}
	

}
